### ISSUE TITLE
Exception in thread "main" java.lang.NumberFormatException:

### ISSUE THREAD

**Issue by okendojo** [wenbostar/PGA#16]
I did run the rtandem successfully but when I am now running the perseGear I get the following error. What could be the problem?

> parserGear(file = idfile, db = dbfile, decoyPrefix="#REV#",xmx=1,thread=4,outdir = "parser_outdir")
Exception in thread "main" java.lang.NumberFormatException: For input string: "PT5786.951S"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at cn.bgi.MainRun.run(MainRun.java:317)
	at cn.bgi.MainRun.main(MainRun.java:58)
Warning message:
In system(command = tandemparser, intern = TRUE) :
  running command '/opt/exp_soft/miniconda3/bin/java -Xmx1G -jar "/home/oknjav001/R/x86_64-pc-linux-gnu-library/3.6/PGA/parser4PGA.jar" ".//180731_C0_CH_T016BCG.mzML_xtandem.xml" "/scratch/oknjav001/transcriptomics/proteogenomics/dbcreation/customdb/T042PPD_merge-var.fasta" "pga" "parser_outdir" "#REV#" "VAR" 1 4' had status 1

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.3.so

locale:
 [1] LC_CTYPE=en_ZA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_ZA.UTF-8        LC_COLLATE=en_ZA.UTF-8    
 [5] LC_MONETARY=en_ZA.UTF-8    LC_MESSAGES=en_ZA.UTF-8   
 [7] LC_PAPER=en_ZA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_ZA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] PGA_1.16.0           rTANDEM_1.26.0       Rcpp_1.0.1          
 [4] XML_3.99-0.3         data.table_1.12.8    Biostrings_2.54.0   
 [7] XVector_0.26.0       GenomicRanges_1.38.0 GenomeInfoDb_1.22.1 
[10] IRanges_2.20.2       S4Vectors_0.24.4     BiocGenerics_0.32.0 

loaded via a namespace (and not attached):
 [1] Biobase_2.46.0              httr_1.4.1                 
 [3] bit64_0.9-7                 assertthat_0.2.1           
 [5] askpass_1.1                 BiocFileCache_1.10.2       
 [7] blob_1.2.1                  BSgenome_1.54.0            
 [9] GenomeInfoDbData_1.2.2      Rsamtools_2.2.3            
[11] progress_1.2.2              pillar_1.4.4               
[13] RSQLite_2.2.0               lattice_0.20-38            
[15] glue_1.3.1                  digest_0.6.25              
[17] RColorBrewer_1.1-2          colorspace_1.4-1           
[19] Matrix_1.2-17               plyr_1.8.6                 
[21] pkgconfig_2.0.3             pheatmap_1.0.12            
[23] customProDB_1.26.1          biomaRt_2.42.1             
[25] zlibbioc_1.32.0             purrr_0.3.4                
[27] scales_1.1.0                processx_3.4.2             
[29] BiocParallel_1.20.1         tibble_3.0.1               
[31] openssl_1.4.1               ggplot2_3.3.0              
[33] AhoCorasickTrie_0.1.0       ellipsis_0.3.0             
[35] SummarizedExperiment_1.16.1 GenomicFeatures_1.38.2     
[37] magrittr_1.5                crayon_1.3.4               
[39] memoise_1.1.0               ps_1.3.2                   
[41] MASS_7.3-51.4               tools_3.6.0                
[43] prettyunits_1.1.1           hms_0.5.3                  
[45] lifecycle_0.2.0             matrixStats_0.56.0         
[47] stringr_1.4.0               munsell_0.5.0              
[49] DelayedArray_0.12.3         AnnotationDbi_1.48.0       
[51] ade4_1.7-15                 compiler_3.6.0             
[53] rlang_0.4.6                 grid_3.6.0                 
[55] RCurl_1.98-1.2              VariantAnnotation_1.32.0   
[57] rappdirs_0.3.1              bitops_1.0-6               
[59] gtable_0.3.0                DBI_1.1.0                  
[61] curl_4.3                    R6_2.4.1                   
[63] GenomicAlignments_1.22.1    Nozzle.R1_1.1-1            
[65] dplyr_0.8.5                 rtracklayer_1.46.0         
[67] seqinr_3.6-1                bit_1.1-15.2               
[69] readr_1.3.1                 stringi_1.4.3              
[71] vctrs_0.2.4                 dbplyr_1.4.3               
[73] tidyselect_1.0.0

**Comment by wenbostar** [comment]
Hi Javan，
Could you please try to use MGF format MS/MS data not mzML for peptide identification? This may be the reason that your mzML is not compatible with R version X!Tandem.
Bo
